### ISSUE TITLE
I am making a Netflix logo using css

### ISSUE THREAD

**Issue by karankartikeya** [salil-naik/css-art-gallery#122]
Please assign this issue to me so I can start working.

**Comment by salil-naik** [comment]
Hi. Someone has already opened an issue to work on the Netflix logo. Please work on something else. You may edit this issue and change the title.

**Comment by karankartikeya** [comment]
Sure sir,
 I will edit this issue soon.

**Comment by salil-naik** [comment]
Hi @karankartikeya, do you wish to work on this issue?
