### ISSUE TITLE
I am testing my css-art on the web <css-art-gallery>

### ISSUE THREAD

**Issue by araiz-mabs** [salil-naik/css-art-gallery#125]
"test your component, import your component to app.js."

When I do this my art doesn't show up on the webpage, and I tried this also as asked by the css-art-gallery pm:
"Inside the art folder, there is index.js. Export your component there first. Then import it to App.js"

How do I show-up my art on the web-page, as I have been trying to make the same art(just for practise before making my own art)
 you showed in the video and its not appearing.

**Comment by salil-naik** [comment]
Hi. Inside the art folder, there is index.js file. You have to first export your art. 

Then import that art into App.js.
