### ISSUE TITLE
I am making a <Android> logo

### ISSUE THREAD

**Issue by codeaholic-shub** [salil-naik/css-art-gallery#13]
Hey @salil-naik ,
I want to make Android logo .

**Comment by Jaagrav** [comment]
Can I work on this as well please?

**Comment by codeaholic-shub** [comment]
> Can I work on this as well please?

No , keep trying on other issues bro , I'm beginner and you have already done ,let me do first , if I'm unable then surely you can work !

**Comment by salil-naik** [comment]
Hi @codeaholic-shub, are you still working on this? If not, I'll assign it to @Jaagrav

**Comment by Jaagrav** [comment]
> Can I work on this as well please?
> 
> No , keep trying on other issues bro , I'm beginner and you have already done ,let me do first , if I'm unable then surely you can work !

Hahaha 😛😛😛

**Comment by salil-naik** [comment]
@Jaagrav Are you working on this? If not, I'll close the issue.
