### ISSUE TITLE
I am making a cool cursor game!

### ISSUE THREAD

**Issue by Sakshi2607-app** [salil-naik/css-art-gallery#14]

**Comment by salil-naik** [comment]
@Sakshi2607-app someone has already made the GitHub logo. Try something else. And it need not be a logo, it could be anything.

**Comment by salil-naik** [comment]
You may just edit this issue and change the art name.

**Comment by Sakshi2607-app** [comment]
Hi ,

Can i make a dynamic file like it works with help of a cursor?

**Comment by salil-naik** [comment]
@Sakshi2607-app are you still working on this? If not I'll close the issue.
