### ISSUE TITLE
I am making a Whatsapp logo

### ISSUE THREAD

**Issue by Charu271** [salil-naik/css-art-gallery#29]
Please assign it to me

**Comment by salil-naik** [comment]
It's already made. Edit the title and replace 'Microsoft logo' with something else. The art could be anything and need not be a logo.

**Comment by Charu271** [comment]
@salil-naik Can i continue with whatsapp logo

**Comment by salil-naik** [comment]
Yes @Charu271, please go ahead.

**Comment by salil-naik** [comment]
Hi, @Charu271 are you still working on this issue? If not, let me know.

**Comment by Charu271** [comment]
Yeah Its almost done

**Comment by Charu271** [comment]
@salil-naik made the pull request
