### ISSUE TITLE
I am making a Moon

### ISSUE THREAD

**Issue by salil-naik** [salil-naik/css-art-gallery#3]

**Comment by Nishayadav-bit** [comment]
Hey @salil-naik , I'm a GSSOC'21 participant . I would like to work on this issue please assign to me.

**Comment by salil-naik** [comment]
> Hey @salil-naik , I'm a GSSOC'21 participant . I would like to work on this issue please assign to me.

Hi. This is not a GSSoC repository. It is just a fun activity for the participants.
