### ISSUE TITLE
I am making a Animated heart

### ISSUE THREAD

**Issue by sonalisonawane** [salil-naik/css-art-gallery#44]

**Comment by salil-naik** [comment]
Hi @sonalisonawane are you still working on this issue? If not I'll assign it to someone else. Let me know.

**Comment by sonalisonawane** [comment]
Sorry @salil-naik sir for delay ,I had worked on this issue but ,I was facing problem about local server was not running and giving some kind of error ,I will solve that and submit this issue asap
